---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: laptop-bluefin
# description will be included in the image's metadata
description: Personal Bluefin image with GNOME Mutter tearing support.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/projectbluefin/bluefin
image-version: testing

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: packages.yml
  - from-file: mutter.yml
  - from-file: flatpaks.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
