RUN set -eux; \
    dnf5 install -y \
      bash-completion cairo-devel colord-devel gcc gcc-c++ git glib2-devel \
      gnome-desktop4-devel graphene-devel gtk4-devel \
      gobject-introspection-devel libcanberra-devel libdisplay-info-devel \
      libdrm-devel libei-devel libgudev-devel libinput-devel libwacom-devel \
      libwayland-devel libX11-devel libXau-devel libXcomposite-devel \
      libXcursor-devel libXdamage-devel libXext-devel libXfixes-devel \
      libXi-devel libXinerama-devel libXrandr-devel libxkbcommon-devel \
      lcms2-devel mesa-libgbm-devel meson ninja-build pango-devel \
      pipewire-devel pixman-devel pkgconf-pkg-config python3-docutils \
      python3-gobject sysprof-devel wayland-protocols \
      xorg-x11-server-Xwayland; \
    workdir="$(mktemp -d)"; \
    trap 'rm -rf "$workdir"' EXIT; \
    git clone --filter=blob:none \
      https://github.com/franzjeger/mutter-tearing-arch.git "$workdir/tearing"; \
    git -C "$workdir/tearing" checkout --detach \
      e41f26e15eab654163a61e5a2e5a3fc34e4d38d1; \
    git clone --filter=blob:none --branch 50.4 \
      https://github.com/GNOME/mutter.git "$workdir/mutter"; \
    test "$(git -C "$workdir/mutter" rev-parse HEAD)" = \
      8fe247a25a5b773e506c3f5f442ca0b7e3d5dc97; \
    git -C "$workdir/tearing" show \
      'e41f26e15eab654163a61e5a2e5a3fc34e4d38d1:mutter-tearing-50.4.patch' \
      > "$workdir/mutter-tearing.patch"; \
    git -C "$workdir/mutter" apply --check "$workdir/mutter-tearing.patch"; \
    git -C "$workdir/mutter" apply "$workdir/mutter-tearing.patch"; \
    meson setup "$workdir/mutter-build" "$workdir/mutter" \
      --prefix=/usr --libdir=lib64 \
      -Ddocs=false -Degl_device=true -Dinstalled_tests=false \
      -Dtests=disabled -Dwayland_eglstream=true; \
    meson compile -C "$workdir/mutter-build"; \
    meson install -C "$workdir/mutter-build"; \
    glib-compile-schemas /usr/share/glib-2.0/schemas
